---
### Default configuration values for IdP utilities.
###
### Make a copy of this file named “config.yml”.
### Uncomment an entry to change its value.

### Root directory for finding Shibboleth IdP config and metadata.
# shibboleth-root: /opt/shibboleth-idp

### Path substitutions and other properties that we need values for.
### `idp.home` defaults to the value of `shibboleth-root` above.
### Other variables or nested substitutions are not allowed.
# properties:
#   idp.home: shibboleth-root

### A list of metadata files that must always be present.
### This should include the IdP’s metadata file, usually in
### `conf/idp.properties` as `idp.entityID.metadataFile`.
### Substitution for keys in `properties` above is allowed.
### Use quotes if the string begins with a `%`.
# metadata-require:
#   - "%{idp.home}/metadata/idp-metadata.xml"

### A list of metadata files not to report as extraneous
### or parse for content validation. No defaults.
# metadata-ignore:

### Path to xmllint. Set to false if it is not installed.
# xmllint: /usr/bin/xmllint

### Hostname for attribute resolution. Defaults to current host’s FQDN,
### but `localhost` is allowed. SSL cert is not verified.
# hostname: localhost

### Test SP for attribute resolution. This should be an SP that gets
### all known attributes released to it. Use it with attributes.py
### by specifying `-r test`. There is no default; if this value is not
### set, the string “test” will be used as the requester’s Entity ID.
# test-sp: https://sp.example.edu
